import React from "react";
import bg2 from "@/public/contact-bg.jpeg";
import Image from "next/image";
import { MailIcon, PhoneCallIcon } from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "Contact-Raoufs portfolio",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return (
    <div className="min-h-screen relative">
      <Image
        src={bg2}
        className="-z-50 fixed w-full h-full object-cover object-center"
        alt="background"
      />
      <div className="flex justify-center items-center w-screen h-screen">
        <div className="max-w-4xl text-center space-y-10">
          <h2 className="text-accent text-4xl font-extrabold">
            Beam Me a Message
          </h2>
          <p className="text-white capitalize">
            Whether you&apos; re looking to build an innovative website, launch
            a new project, or just explore ideas, I&apos;m here to help. With a
            passion for crafting digital experiences that are both out of this
            world and grounded in quality, I&apos;m ready to take on the next
            big challenge. Lets connect and see how we can turn your vision into
            reality, no matter how far or wide the journey may take us.
          </p>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-2">
            <Link href="tel:01111653752">
              <div className="flex flex-col">
                <div className="custom-bg">
                  <div className="text-white flex justify-center items-center gap-5">
                    <PhoneCallIcon /> 01111653752
                  </div>
                </div>
              </div>
            </Link>
            <Link href="mailto:mohamedraouf27@gmail.com">
              <div className="flex flex-col">
                <div className="custom-bg">
                  <div className="text-white flex justify-center items-center gap-5">
                    <MailIcon /> mohamedraouf27@gmail.com
                  </div>
                </div>
              </div>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContactPage;
