import RenderModel from "@/app/_components/RenderModel";
import Image from "next/image";
import React from "react";
import bg from "@/public/night-space.jpeg";
import Astronaut from "@/app/_components/Astronaut";
import { projectsData } from "@/data";
import ProjectLayout from "./_component/ProjectLayout";

export const metadata = {
  title: "Projects-Raouf's portfolio",
  description: "Generated by create next app",
};

const ProjectsPage = () => {
  return (
    <div className="min-h-screen relative ">
      <Image
        src={bg}
        className="-z-50 fixed w-full h-full object-cover object-center"
        alt="background"
      />
      <div className="container mx-auto grid justify-stretch items-center pt-[30rem] lg:pt-40 pb-10">
        <div className="max-w-4xl z-10">
          <div className="flex flex-col gap-2">
            {projectsData.map((project) => (
              <ProjectLayout key={project.id} project={project} />
            ))}
          </div>
        </div>
      </div>

      <div className="w-full h-screen fixed mt-10 top-0 left-0 lg:top-[20%] lg:left-[40%] xl:left-[30%]">
        <RenderModel position={[-0.1, 0.1, 0.2]} intensity={0.1}>
          <Astronaut animation={"moon_walk"} position={[0, 0, 0]} />
        </RenderModel>
      </div>
    </div>
  );
};

export default ProjectsPage;
