import React from "react";
import bg2 from "@/public/projectId-background2.jpeg";
import Image from "next/image";
import RenderModel from "@/app/_components/RenderModel";
import Rover from "@/app/_components/Rover";

export const metadata = {
  title: "About-Raouf's portfolio",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="min-h-screen relative">
      <Image
        src={bg2}
        className="-z-50 fixed w-full h-full object-cover object-center"
        alt="background"
      />

      <div className="z-300 absolute h-full w-full top-0 left-0">
        <RenderModel position={[0.1, 0.1, 0.2]} intensity={0.2}>
          <Rover />
        </RenderModel>
        <div className="container mx-auto">
          <div className="grid grid-cols-12 gap-5">
            <div className="col-span-12 lg:col-span-8 row-span-2 custom-bg">
              <h2 className="uppercase font-bold text-accent my-2 text-lg">
                About me
              </h2>
              <div className="text-white space-y-3">
                <p>
                  Im a web developer with 2 years of agency experience, skilled
                  in WordPress ,HTML, CSS, JavaScript and modern frameworks like
                  Nextjs
                </p>
                <p>
                  Throughout my journey, Ive built a variety of projects, from
                  e-commerce websites to dynamic landing pages, using platforms
                  like WordPress, Salla, Zid, OpenCart, and cutting-edge tools
                  like Nextjs, Prisma and TailwindCSS.
                </p>
                <p>
                  I thrive on exploring new technologies and pushing the
                  boundaries of whats possible in web development. Just like
                  space exploration, I believe the digital world is full of
                  uncharted territories waiting to be discovered. My mission is
                  to create innovative, user-friendly websites that drive
                  results and offer seamless experiences. Whether it's an
                  e-commerce platform or a landing page, I aim to build
                  solutions that are as efficient as they are visually engaging.
                </p>
                <p>
                  Join me as we venture into the future of the web — where the
                  possibilities are limitless, and every project is a new
                  frontier.
                </p>
              </div>
            </div>

            <div className="col-span-12 lg:col-span-4 custom-bg flex items-center">
              <h2 className="text-accent font-semibold uppercase">
                <span className="text-6xl font-extrabold text-white">2+</span>
                years of experience
              </h2>
            </div>
            <div className="col-span-12 lg:col-span-4 custom-bg items-center flex">
              <h2 className="text-accent font-semibold uppercase">
                <span className="text-6xl font-extrabold text-white">25+</span>
                completed projects
              </h2>
            </div>

            <div className="col-span-12 custom-bg my-10">
              <h2 className="font-bold text-accent my-2 text-xl">
                Technologies I Navigate Through the Journey
              </h2>
              <div className="grid grid-cols-2 lg:grid-cols-8 gap-5 my-5">
                <span className="bg-accent text-white rounded-3xl px-2 py-1 uppercase text-center">
                  Wordpress
                </span>
                <span className="bg-accent text-white rounded-3xl px-2 py-1 uppercase text-center">
                  html
                </span>
                <span className="bg-accent text-white rounded-3xl px-2 py-1 uppercase text-center">
                  css
                </span>
                <span className="bg-accent text-white rounded-3xl px-2 py-1 uppercase text-center">
                  JavaScript
                </span>
                <span className="bg-accent text-white rounded-3xl px-2 py-1 uppercase text-center">
                  Nextjs
                </span>
                <span className="bg-accent text-white rounded-3xl px-2 py-1 uppercase text-center">
                  prisma
                </span>
                <span className="bg-accent text-white rounded-3xl px-2 py-1 uppercase text-center">
                  tailwindcss
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="absolute top-[60%] left-[50%] -translate-x-[50%] ">
        <div className="custom-bg w-[100vw] lg:w-[40vw]">
          <p className="text-white capitalize text-center my-2">my portfolio</p>
          <h1 className="text-3xl uppercase font-bold text-accent lg:text-4xl text-center">
            Journey Beyond the Horizon
          </h1>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
