"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nasa-curiosity-clean-0696a383f3e841d2b5c7636ee8a58aba
Title: NASA Curiosity (Clean)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Rover(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/rover-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions["Take 01"];
    if (action) {
      action.play();
    }

    // Optionally stop the animation when the component unmounts
    return () => {
      if (action) {
        action.stop();
      }
    };
  }, [actions]);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[0.1, 0.1, 0.1]}
      position={[0, 0, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Root" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="_root_p">
            <group name="Chassis" position={[0, -0.055, 0.886]}>
              <mesh
                name="Chassis_0"
                castShadow
                receiveShadow
                geometry={nodes.Chassis_0.geometry}
                material={materials.tex_03}
              />
              <mesh
                name="Chassis_1"
                castShadow
                receiveShadow
                geometry={nodes.Chassis_1.geometry}
                material={materials.tex_01}
              />
              <mesh
                name="Chassis_2"
                castShadow
                receiveShadow
                geometry={nodes.Chassis_2.geometry}
                material={materials.tex_02}
              />
              <mesh
                name="Chassis_3"
                castShadow
                receiveShadow
                geometry={nodes.Chassis_3.geometry}
                material={materials.tex_05}
              />
              <group name="RAD" position={[0.348, -0.009, 0.236]} scale={0.062}>
                <mesh
                  name="RAD_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RAD_0.geometry}
                  material={materials.tex_01}
                />
              </group>
              <group
                name="REMS"
                position={[-0.224, -0.492, 0.236]}
                rotation={[0, 0, -2.756]}
                scale={[0.024, 0.03, 0.03]}
              >
                <mesh
                  name="REMS_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.REMS_0.geometry}
                  material={materials.tex_01}
                />
              </group>
              <group name="DAN_L" position={[0.577, 0.927, -0.014]}>
                <mesh
                  name="DAN_L_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.DAN_L_0.geometry}
                  material={materials.tex_02}
                />
              </group>
              <group name="DAN_R" position={[-0.577, 0.918, 0.002]}>
                <mesh
                  name="DAN_R_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.DAN_R_0.geometry}
                  material={materials.tex_02}
                />
              </group>
              <group name="sundial" position={[-0.514, 0.436, 0.43]}>
                <mesh
                  name="sundial_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.sundial_0.geometry}
                  material={materials.tex_01}
                />
              </group>
              <group name="HazCam_-_rear" position={[0, 1.108, -0.064]}>
                <mesh
                  name="HazCam_-_rear_0"
                  castShadow
                  receiveShadow
                  geometry={nodes["HazCam_-_rear_0"].geometry}
                  material={materials.tex_02}
                />
              </group>
              <group name="HazCam_-_front" position={[0.04, -0.822, -0.16]}>
                <mesh
                  name="HazCam_-_front_0"
                  castShadow
                  receiveShadow
                  geometry={nodes["HazCam_-_front_0"].geometry}
                  material={materials.tex_02}
                />
              </group>
              <group name="MARDI001" position={[0.648, -0.609, -0.153]}>
                <mesh
                  name="MARDI001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.MARDI001_0.geometry}
                  material={materials.tex_03}
                />
              </group>
              <group name="CheMin" position={[0.123, -0.622, 0.242]}>
                <mesh
                  name="CheMin_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.CheMin_0.geometry}
                  material={materials.tex_01}
                />
              </group>
              <group name="SAM" position={[-0.164, -0.626, 0.243]}>
                <mesh
                  name="SAM_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.SAM_0.geometry}
                  material={materials.tex_01}
                />
              </group>
              <group name="body001">
                <mesh
                  name="body001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.body001_0.geometry}
                  material={materials.tex_03}
                />
              </group>
              <group name="radiators">
                <mesh
                  name="radiators_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.radiators_0.geometry}
                  material={materials.tex_03}
                />
              </group>
              <group name="RTG" position={[0, 1.26, 0.264]}>
                <mesh
                  name="RTG_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RTG_0.geometry}
                  material={materials.tex_03}
                />
              </group>
              <group name="antenna_LG" position={[0.495, 0.992, 0.584]}>
                <mesh
                  name="antenna_LG_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.antenna_LG_0.geometry}
                  material={materials.tex_02}
                />
              </group>
              <group name="antenna_UHF" position={[-0.505, 1.138, 0.734]}>
                <mesh
                  name="antenna_UHF_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.antenna_UHF_0.geometry}
                  material={materials.tex_02}
                />
              </group>
              <group name="cover_02" position={[-0.277, -0.689, 0.229]}>
                <mesh
                  name="cover_02_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.cover_02_0.geometry}
                  material={materials.tex_01}
                />
              </group>
              <group name="cover_03" position={[-0.155, -0.516, 0.229]}>
                <mesh
                  name="cover_03_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.cover_03_0.geometry}
                  material={materials.tex_01}
                />
              </group>
              <group name="cover_01" position={[0.213, -0.563, 0.227]}>
                <mesh
                  name="cover_01_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.cover_01_0.geometry}
                  material={materials.tex_01}
                />
              </group>
            </group>
            <group name="body" position={[0, -0.055, 0.886]}>
              <mesh
                name="body_0"
                castShadow
                receiveShadow
                geometry={nodes.body_0.geometry}
                material={materials.tex_01}
              />
              <mesh
                name="body_1"
                castShadow
                receiveShadow
                geometry={nodes.body_1.geometry}
                material={materials.tex_02}
              />
              <mesh
                name="body_2"
                castShadow
                receiveShadow
                geometry={nodes.body_2.geometry}
                material={materials.tex_04}
              />
              <mesh
                name="body_3"
                castShadow
                receiveShadow
                geometry={nodes.body_3.geometry}
                material={materials.tex_03}
              />
              <mesh
                name="body_4"
                castShadow
                receiveShadow
                geometry={nodes.body_4.geometry}
                material={materials["tex_01.001"]}
              />
              <mesh
                name="body_5"
                castShadow
                receiveShadow
                geometry={nodes.body_5.geometry}
                material={materials.parts_AO}
              />
              <group
                name="arm_01001"
                position={[0.451, -1.058, 0.112]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <mesh
                  name="arm_01001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.arm_01001_0.geometry}
                  material={materials.tex_03}
                />
                <mesh
                  name="arm_01001_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.arm_01001_1.geometry}
                  material={materials.tex_01}
                />
                <group
                  name="MAHLI_cal_target"
                  position={[0, 0, -0.194]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    name="MAHLI_cal_target_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.MAHLI_cal_target_0.geometry}
                    material={materials.tex_05}
                  />
                </group>
                <group
                  name="arm_02001"
                  position={[-0.004, -0.161, -0.166]}
                  rotation={[-0.262, 0, 0]}
                >
                  <mesh
                    name="arm_02001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.arm_02001_0.geometry}
                    material={materials.tex_01}
                  />
                  <mesh
                    name="arm_02001_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.arm_02001_1.geometry}
                    material={materials.tex_03}
                  />
                  <mesh
                    name="arm_02001_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.arm_02001_2.geometry}
                    material={materials.tex_04}
                  />
                  <mesh
                    name="arm_02001_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.arm_02001_3.geometry}
                    material={materials.tex_05}
                  />
                  <group
                    name="arm_03001"
                    position={[0.071, -0.825, 0.001]}
                    rotation={[-1.222, 0, 0]}
                  >
                    <mesh
                      name="arm_03001_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.arm_03001_0.geometry}
                      material={materials.tex_03}
                    />
                    <mesh
                      name="arm_03001_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.arm_03001_1.geometry}
                      material={materials.tex_01}
                    />
                    <mesh
                      name="arm_03001_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.arm_03001_2.geometry}
                      material={materials.tex_04}
                    />
                    <mesh
                      name="arm_03001_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.arm_03001_3.geometry}
                      material={materials.tex_05}
                    />
                    <group
                      name="arm_04001"
                      position={[-0.159, 0.001, 0.783]}
                      rotation={[1.484, 0, 0]}
                    >
                      <mesh
                        name="arm_04001_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.arm_04001_0.geometry}
                        material={materials.tex_03}
                      />
                      <mesh
                        name="arm_04001_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.arm_04001_1.geometry}
                        material={materials.tex_01}
                      />
                      <group
                        name="arm_05_head001"
                        position={[0.074, 0.101, 0.144]}
                        rotation={[0, 0, -0.559]}
                      >
                        <mesh
                          name="arm_05_head001_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.arm_05_head001_0.geometry}
                          material={materials.tex_04}
                        />
                        <group name="CHIMERA" position={[0.208, -0.048, 0.149]}>
                          <mesh
                            name="CHIMERA_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.CHIMERA_0.geometry}
                            material={materials.tex_04}
                          />
                          <mesh
                            name="CHIMERA_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.CHIMERA_1.geometry}
                            material={materials.tex_05}
                          />
                        </group>
                        <group name="Drill" position={[-0.036, 0.001, 0.176]}>
                          <mesh
                            name="Drill_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Drill_0.geometry}
                            material={materials.tex_04}
                          />
                          <mesh
                            name="Drill_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Drill_1.geometry}
                            material={materials.tex_05}
                          />
                        </group>
                        <group
                          name="Dust_Removal_Tool"
                          position={[-0.217, -0.072, 0.16]}
                        >
                          <mesh
                            name="Dust_Removal_Tool_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Dust_Removal_Tool_0.geometry}
                            material={materials.tex_04}
                          />
                        </group>
                        <group name="MAHLI" position={[-0.192, 0.094, 0.141]}>
                          <mesh
                            name="MAHLI_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.MAHLI_0.geometry}
                            material={materials.tex_04}
                          />
                          <group
                            name="MAHLI_LED_03"
                            position={[-0.041, 0.015, 0.01]}
                            rotation={[-1.54, -0.993, -1.023]}
                            scale={0.002}
                          >
                            <mesh
                              name="MAHLI_LED_03_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.MAHLI_LED_03_0.geometry}
                              material={materials.white_LED}
                            />
                          </group>
                          <group
                            name="MAHLI_LED_02"
                            position={[-0.026, 0.039, -0.004]}
                            rotation={[-1.54, -0.993, -1.023]}
                            scale={0.002}
                          >
                            <mesh
                              name="MAHLI_LED_02_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.MAHLI_LED_02_0.geometry}
                              material={materials.white_LED}
                            />
                          </group>
                          <group
                            name="MAHLI_LED_04"
                            position={[-0.041, 0.015, 0.015]}
                            rotation={[-1.54, -0.993, -1.023]}
                            scale={0.002}
                          >
                            <mesh
                              name="MAHLI_LED_04_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.MAHLI_LED_04_0.geometry}
                              material={materials.white_LED}
                            />
                          </group>
                          <group
                            name="MAHLI_LED_01"
                            position={[-0.024, 0.041, 0]}
                            rotation={[-1.54, -0.993, -1.023]}
                            scale={0.002}
                          >
                            <mesh
                              name="MAHLI_LED_01_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.MAHLI_LED_01_0.geometry}
                              material={materials.white_LED}
                            />
                          </group>
                          <group
                            name="MAHLI_lens_cover_p"
                            position={[-0.034, 0.042, 0.027]}
                            rotation={[2.7, -0.289, 0.506]}
                          >
                            <group
                              name="MAHLI_lens_cover"
                              position={[0.002, -0.003, 0.011]}
                              rotation={[-2.619, -0.018, 0.577]}
                            >
                              <mesh
                                name="MAHLI_lens_cover_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.MAHLI_lens_cover_0.geometry}
                                material={materials.tex_04}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="APXS" position={[0.189, 0.153, 0.158]}>
                          <mesh
                            name="APXS_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.APXS_0.geometry}
                            material={materials.tex_04}
                          />
                        </group>
                        <group name="bit_01001" position={[0, -0.179, 0.14]}>
                          <mesh
                            name="bit_01001_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.bit_01001_0.geometry}
                            material={materials.tex_03}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group
                name="bit_02"
                position={[-0.463, -1.057, -0.181]}
                rotation={[0, 0, -0.489]}
              >
                <mesh
                  name="bit_02_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bit_02_0.geometry}
                  material={materials.tex_03}
                />
              </group>
              <group
                name="bit_03"
                position={[-0.159, -1.041, -0.098]}
                rotation={[0, 0, 0.192]}
              >
                <mesh
                  name="bit_03_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bit_03_0.geometry}
                  material={materials.tex_03}
                />
              </group>
              <group name="antenna_HG_01" position={[0.475, 0.515, 0.344]}>
                <mesh
                  name="antenna_HG_01_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.antenna_HG_01_0.geometry}
                  material={materials.tex_02}
                />
                <group
                  name="antenna_HG_02_p"
                  position={[0.036, 0.078, 0.133]}
                  rotation={[0, 0, -0.436]}
                >
                  <group
                    name="antenna_HG_03"
                    position={[-0.33, -0.502, -0.135]}
                    rotation={[0, 0, -2.705]}
                  >
                    <mesh
                      name="antenna_HG_03_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.antenna_HG_03_0.geometry}
                      material={materials.tex_02}
                    />
                  </group>
                </group>
              </group>
              <group
                name="lens_covers_front"
                position={[-0.091, -0.851, -0.198]}
                rotation={[2.366, 0, 0]}
              >
                <mesh
                  name="lens_covers_front_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.lens_covers_front_0.geometry}
                  material={materials.parts_AO}
                />
              </group>
              <group
                name="lens_covers_rear"
                position={[0.501, 1.093, -0.138]}
                rotation={[2.88, 0, 0]}
              >
                <mesh
                  name="lens_covers_rear_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.lens_covers_rear_0.geometry}
                  material={materials.parts_AO}
                />
              </group>
              <group
                name="mast_p"
                position={[-0.558, -0.661, 0.339]}
                rotation={[-Math.PI / 2, 0.995, Math.PI / 2]}
              >
                <group
                  name="mast_01001"
                  position={[-0.055, -0.014, 0.183]}
                  rotation={[0, 0, -0.576]}
                >
                  <mesh
                    name="mast_01001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.mast_01001_0.geometry}
                    material={materials.tex_04}
                  />
                  <group
                    name="mast_02001"
                    position={[0.038, 0.043, 0.291]}
                    rotation={[0, 0, 2.147]}
                  >
                    <mesh
                      name="mast_02001_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mast_02001_0.geometry}
                      material={materials.tex_04}
                    />
                    <group name="mast_03001" position={[0.021, 0, 0.202]}>
                      <mesh
                        name="mast_03001_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.mast_03001_0.geometry}
                        material={materials.tex_04}
                      />
                      <group name="ChemCam">
                        <mesh
                          name="ChemCam_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.ChemCam_0.geometry}
                          material={materials.tex_04}
                        />
                      </group>
                      <group name="MastCam">
                        <mesh
                          name="MastCam_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.MastCam_0.geometry}
                          material={materials.tex_04}
                        />
                      </group>
                      <group name="NavCam">
                        <mesh
                          name="NavCam_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.NavCam_0.geometry}
                          material={materials.tex_04}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="mast_01000" position={[-0.04, -0.001, 0.102]}>
                    <mesh
                      name="mast_01000_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mast_01000_0.geometry}
                      material={materials.tex_04}
                    />
                  </group>
                </group>
              </group>
              <group
                name="suspension_xmember"
                position={[0, 0.197, 0.288]}
                rotation={[0, 0, 0.007]}
              >
                <mesh
                  name="suspension_xmember_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.suspension_xmember_0.geometry}
                  material={materials.tex_02}
                />
                <mesh
                  name="suspension_xmember_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.suspension_xmember_1.geometry}
                  material={materials.tex_05}
                />
              </group>
              <group
                name="suspension_axel_L"
                position={[0.641, -0.159, -0.011]}
              >
                <mesh
                  name="suspension_axel_L_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.suspension_axel_L_0.geometry}
                  material={materials["tex_03.002"]}
                />
                <group
                  name="suspension_rod_L"
                  position={[0.031, 0, 0.269]}
                  rotation={[0.01, 0, Math.PI]}
                >
                  <mesh
                    name="suspension_rod_L_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.suspension_rod_L_0.geometry}
                    material={materials.tex_03}
                  />
                </group>
                <group
                  name="suspension_arm_B_L_p"
                  position={[0.153, 0, 0.009]}
                  rotation={[0.892, -0.124, 0.152]}
                >
                  <group
                    name="suspension_arm_B_L"
                    position={[-0.025, 0.364, -0.101]}
                    rotation={[0, 0.196, 0]}
                  >
                    <mesh
                      name="suspension_arm_B_L_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.suspension_arm_B_L_0.geometry}
                      material={materials.tex_03}
                    />
                    <mesh
                      name="suspension_arm_B_L_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.suspension_arm_B_L_1.geometry}
                      material={materials.tex_05}
                    />
                    <group name="Cube_03_p" position={[0.198, 0.39, -0.138]}>
                      <group
                        name="suspension_arm_B2_L"
                        position={[-0.192, 0, 0]}
                        rotation={[-0.743, 0, 0]}
                      >
                        <mesh
                          name="suspension_arm_B2_L_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspension_arm_B2_L_0.geometry}
                          material={materials.tex_03}
                        />
                        <mesh
                          name="suspension_arm_B2_L_1"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspension_arm_B2_L_1.geometry}
                          material={materials.tex_02}
                        />
                        <group
                          name="wheel_02_L"
                          position={[0.394, -0.451, -0.4]}
                        >
                          <mesh
                            name="wheel_02_L_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.wheel_02_L_0.geometry}
                            material={materials.tex_03_n}
                          />
                        </group>
                        <group
                          name="suspension_steer_B_L"
                          position={[0.263, 0.624, -0.001]}
                        >
                          <mesh
                            name="suspension_steer_B_L_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.suspension_steer_B_L_0.geometry}
                            material={materials.tex_03}
                          />
                          <mesh
                            name="suspension_steer_B_L_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.suspension_steer_B_L_1.geometry}
                            material={materials.tex_02}
                          />
                          <group
                            name="wheel_03_L"
                            position={[0, -0.001, -0.399]}
                          >
                            <mesh
                              name="wheel_03_L_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.wheel_03_L_0.geometry}
                              material={materials.tex_03_n}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="suspension_arm_F_L_p"
                  position={[0.154, 0.002, 0.007]}
                  rotation={[-0.849, -0.131, -0.147]}
                >
                  <group name="suspension_arm_F_L" rotation={[0, 0.196, 0]}>
                    <mesh
                      name="suspension_arm_F_L_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.suspension_arm_F_L_0.geometry}
                      material={materials.tex_03}
                    />
                    <mesh
                      name="suspension_arm_F_L_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.suspension_arm_F_L_1.geometry}
                      material={materials.tex_05}
                    />
                    <group name="Cube_01_p" position={[0.263, -0.881, -0.002]}>
                      <group
                        name="suspension_steer_F_L"
                        position={[0, 0, -0.24]}
                        rotation={[0, 0, -0.841]}
                      >
                        <mesh
                          name="suspension_steer_F_L_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspension_steer_F_L_0.geometry}
                          material={materials.tex_03}
                        />
                        <mesh
                          name="suspension_steer_F_L_1"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspension_steer_F_L_1.geometry}
                          material={materials.tex_02}
                        />
                        <group name="wheel_01_L" position={[0, 0, -0.4]}>
                          <mesh
                            name="wheel_01_L_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.wheel_01_L_0.geometry}
                            material={materials.tex_03_n}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="suspension_axel_L2"
                  position={[-0.007, 0, -0.002]}
                  rotation={[0, -0.001, 0]}
                  scale={[-1, 1, 1]}
                >
                  <mesh
                    name="suspension_axel_L2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.suspension_axel_L2_0.geometry}
                    material={materials.tex_03}
                  />
                </group>
              </group>
              <group
                name="suspension_axel_R"
                position={[-0.638, -0.159, -0.011]}
              >
                <mesh
                  name="suspension_axel_R_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.suspension_axel_R_0.geometry}
                  material={materials["tex_03.002"]}
                />
                <group
                  name="suspension_rod_R"
                  position={[-0.033, 0, 0.267]}
                  rotation={[0.017, -0.001, 0.003]}
                >
                  <mesh
                    name="suspension_rod_R_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.suspension_rod_R_0.geometry}
                    material={materials.tex_03}
                  />
                </group>
                <group
                  name="suspension_arm_B_R_p"
                  position={[-0.161, 0, 0.01]}
                  rotation={[0.892, 0.124, -0.152]}
                >
                  <group
                    name="suspension_arm_B_R"
                    position={[0.025, 0.364, -0.101]}
                    rotation={[0, -0.196, 0]}
                  >
                    <mesh
                      name="suspension_arm_B_R_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.suspension_arm_B_R_0.geometry}
                      material={materials.tex_03}
                    />
                    <mesh
                      name="suspension_arm_B_R_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.suspension_arm_B_R_1.geometry}
                      material={materials.tex_05}
                    />
                    <group name="Cube_04_p" position={[-0.198, 0.39, -0.138]}>
                      <group
                        name="suspension_arm_B2_R"
                        position={[0.192, 0, 0]}
                        rotation={[-0.743, 0, 0]}
                      >
                        <mesh
                          name="suspension_arm_B2_R_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspension_arm_B2_R_0.geometry}
                          material={materials.tex_03}
                        />
                        <mesh
                          name="suspension_arm_B2_R_1"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspension_arm_B2_R_1.geometry}
                          material={materials.tex_02}
                        />
                        <group
                          name="suspension_steer_B_R"
                          position={[-0.263, 0.624, -0.001]}
                        >
                          <mesh
                            name="suspension_steer_B_R_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.suspension_steer_B_R_0.geometry}
                            material={materials.tex_03}
                          />
                          <mesh
                            name="suspension_steer_B_R_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.suspension_steer_B_R_1.geometry}
                            material={materials.tex_02}
                          />
                          <group
                            name="wheel_03_R"
                            position={[0, 0.001, -0.399]}
                          >
                            <mesh
                              name="wheel_03_R_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.wheel_03_R_0.geometry}
                              material={materials.tex_03_n}
                            />
                          </group>
                        </group>
                        <group
                          name="wheel_02_R"
                          position={[-0.394, -0.451, -0.4]}
                        >
                          <mesh
                            name="wheel_02_R_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.wheel_02_R_0.geometry}
                            material={materials.tex_03_n}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="suspension_arm_F_R_p"
                  position={[-0.161, 0, 0.01]}
                  rotation={[-0.849, 0.131, 0.147]}
                >
                  <group name="suspension_arm_F_R" rotation={[0, -0.196, 0]}>
                    <mesh
                      name="suspension_arm_F_R_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.suspension_arm_F_R_0.geometry}
                      material={materials.tex_03}
                    />
                    <mesh
                      name="suspension_arm_F_R_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.suspension_arm_F_R_1.geometry}
                      material={materials.tex_05}
                    />
                    <group name="Cube_02_p" position={[-0.263, -0.881, -0.005]}>
                      <group
                        name="suspension_steer_F_R"
                        position={[-0.001, 0, -0.237]}
                        rotation={[0, 0, 0.841]}
                      >
                        <mesh
                          name="suspension_steer_F_R_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspension_steer_F_R_0.geometry}
                          material={materials.tex_03}
                        />
                        <mesh
                          name="suspension_steer_F_R_1"
                          castShadow
                          receiveShadow
                          geometry={nodes.suspension_steer_F_R_1.geometry}
                          material={materials.tex_02}
                        />
                        <group name="wheel_01_R" position={[0, 0, -0.4]}>
                          <mesh
                            name="wheel_01_R_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.wheel_01_R_0.geometry}
                            material={materials.tex_03_n}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="suspension_axel_R2" position={[0.004, 0, -0.002]}>
                  <mesh
                    name="suspension_axel_R2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.suspension_axel_R2_0.geometry}
                    material={materials.tex_03}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/rover-transformed.glb");
